package check

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
)

var (
	skipDirs       = []string{"Godeps", "vendor", "third_party", "testdata"}
	skipSuffixes   = []string{".pb.go", ".pb.gw.go", ".generated.go", "bindata.go", "_string.go"}
	skipFirstLines = []string{"code generated", "generated", "autogenerated", "@generated", "code autogenerated", "auto-generated"}
)

// GoFiles returns a slice of Go filenames
// in a given directory.
func GoFiles(dir string) (filenames, skipped []string, err error) {
	visit := func(fp string, fi os.FileInfo, err error) error {
		// filepath.Walk uses the OS-native separator (backslash on Windows),
		// but the rest of the pipeline (skip checks, display names, file URLs)
		// assumes forward slashes, so normalize early.
		fp = filepath.ToSlash(fp)
		for _, skip := range skipDirs {
			if strings.Contains(fp, fmt.Sprintf("/%s/", skip)) {
				return nil
			}
		}
		if err != nil {
			fmt.Println(err) // can't walk here,
			return nil       // but continue walking elsewhere
		}
		if fi.IsDir() {
			return nil // not a file.  ignore.
		}
		fiName := fi.Name()
		for _, skip := range skipSuffixes {
			if strings.HasSuffix(fiName, skip) {
				skipped = append(skipped, fp)
				return nil
			}
		}
		ext := filepath.Ext(fiName)
		if ext != ".go" {
			return nil
		}

		if autoGenerated(fp) {
			skipped = append(skipped, fp)
			return nil
		}

		filenames = append(filenames, fp)

		return nil
	}

	err = filepath.Walk(dir, visit)

	return filenames, skipped, err
}

// RenameFiles renames the provided filenames to have a ".grc.bk" extension,
// so they will not be considered in future checks.
func RenameFiles(names []string) (err error) {
	for i := range names {
		tmpErr := os.Rename(names[i], names[i]+".grc.bk")
		if tmpErr != nil {
			// save this error, but still continue with other files
			err = tmpErr
		}
	}

	return err
}

// RevertFiles removes the ".grc.bk" extension from files
func RevertFiles(names []string) (err error) {
	for i := range names {
		tmpErr := os.Rename(names[i]+".grc.bk", names[i])
		if tmpErr != nil {
			// save this error, but still continue with other files
			err = tmpErr
		}
	}

	return err
}

// lineCount returns the number of lines in a given file
func lineCount(filepath string) (int, error) {
	out, err := exec.Command("wc", "-l", filepath).Output()
	if err != nil {
		return 0, err
	}

	// wc output is like: 999 filename.go
	count, err := strconv.Atoi(strings.Split(strings.TrimSpace(string(out)), " ")[0])
	if err != nil {
		return 0, fmt.Errorf("could not count lines: %v", err)
	}

	return count, nil
}

// determine whether the Go file was auto-generated
func autoGenerated(fp string) bool {
	file, err := os.Open(fp)
	if err != nil {
		fmt.Println(err)
		return false
	}
	defer file.Close()

	// read first line of file and determine if it might
	// be auto-generated
	scanner := bufio.NewScanner(file)
	scanner.Scan()
	line := strings.ToLower(scanner.Text())
	commentStyles := []string{"// ", "//", "/* ", "/*"}
	for _, skip := range skipFirstLines {
		for i := range commentStyles {
			if strings.HasPrefix(line, commentStyles[i]) && strings.HasPrefix(line[len(commentStyles[i]):], skip) {
				return true
			}
		}
	}
	return false
}

// Error contains the line number and the reason for
// an error output from a command
type Error struct {
	LineNumber  int    `json:"line_number"`
	ErrorString string `json:"error_string"`
}

// FileSummary contains the filename, location of the file
// on GitHub, and all of the errors related to the file
type FileSummary struct {
	Filename string  `json:"filename"`
	FileURL  string  `json:"file_url"`
	Errors   []Error `json:"errors"`
}

// AddError adds an Error to FileSummary
func (fs *FileSummary) AddError(out string) error {
	s := strings.SplitN(out, ":", 2)
	msg := strings.SplitAfterN(s[1], ":", 3)[2]

	e := Error{ErrorString: msg}
	ls := strings.Split(s[1], ":")
	ln, err := strconv.Atoi(ls[0])
	if err != nil {
		return fmt.Errorf("AddError: could not parse %q - %v", out, err)
	}
	e.LineNumber = ln

	fs.Errors = append(fs.Errors, e)

	return nil
}

func displayFilename(filename string) string {
	sp := strings.Split(filename, "@")
	if len(sp) < 2 {
		return filename
	}

	fsp := strings.Split(sp[1], "/")

	return strings.Join(fsp[1:], "/")
}

// borrowed from github.com/client9/gosupplychain
// MIT LICENSE: https://github.com/client9/gosupplychain/blob/master/LICENSE
func goPkgInToGitHub(name string) string {
	dir := ""
	var pkgversion string
	var user string
	parts := strings.Split(name, "/")
	if len(parts) < 2 {
		return ""
	}
	if parts[0] != "gopkg.in" {
		return ""
	}

	idx := strings.Index(parts[1], ".")
	if idx != -1 {
		pkgversion = parts[1]
		if len(parts) > 2 {
			dir = "/" + strings.Join(parts[2:], "/")
		}
	} else {
		if len(parts) < 3 {
			return ""
		}
		user = parts[1]
		pkgversion = parts[2]
		if len(parts) > 3 {
			dir = "/" + strings.Join(parts[3:], "/")
		}
	}
	idx = strings.Index(pkgversion, ".")
	if idx == -1 {
		return ""
	}
	pkg := pkgversion[:idx]
	if user == "" {
		user = "go-" + pkg
	}
	version := pkgversion[idx+1:]
	if version == "v0" {
		version = "master"
	}

	return "https://github.com/" + user + "/" + pkg + "/blob/" + version + dir
}

func fileURL(filename string) string {
	f := displayFilename(filename)

	fsp := strings.Split(filename, "@")

	repo := strings.TrimPrefix(fsp[0], "/")

	var ver string
	if len(fsp) > 1 {
		verSp := strings.Split(fsp[1], "/")
		ver = verSp[0]
	}

	var fileURL string
	base := strings.TrimPrefix(repo, "_repos/src/")
	switch {
	case strings.HasPrefix(base, "golang.org/x/"):
		var pkg string
		if len(strings.Split(base, "/")) >= 3 {
			pkg = strings.Split(base, "/")[2]
		}

		return fmt.Sprintf("https://github.com/golang/%s/blob/master%s", pkg, strings.TrimPrefix(filename, "/"+base))
	case strings.HasPrefix(base, "github.com/"):
		if len(strings.Split(base, "/")) == 4 {
			base = strings.Join(strings.Split(base, "/")[0:3], "/")
		}

		if ver != "" {
			if strings.Contains(ver, "-") {
				verSp := strings.Split(ver, "-")
				if len(verSp) > 2 {
					ver = strings.Split(ver, "-")[2]
				}
			}

			if strings.Contains(ver, "+incompatible") {
				ver = strings.TrimSuffix(ver, "+incompatible")
			}

			return fmt.Sprintf("https://%s/blob/%s/%s", base, ver, f)
		}

		return fmt.Sprintf("https://%s/blob/master%s", base, strings.TrimPrefix(filename, "/"+base))
	case strings.HasPrefix(base, "gopkg.in/"):
		return goPkgInToGitHub(base) + strings.TrimPrefix(filename, "/"+base)
	}

	return fileURL
}

func makeFilename(fn string) string {
	sp := strings.Split(fn, "/")
	switch {
	case strings.HasPrefix(fn, "/github.com"):
		if len(sp) > 3 {
			return strings.Join(sp[3:], "/")
		}
	case strings.HasPrefix(fn, "/golang.org/x"):
		if len(sp) > 3 {
			return strings.Join(sp[3:], "/")
		}
	case strings.HasPrefix(fn, "/gopkg.in"):
		if len(sp) > 3 {
			return strings.Join(sp[3:], "/")
		}
	}

	return fn
}

// normalizeToolLine converts a single line of a native tool's output into the
// canonical "file:line:col: message" form that AddError understands. It returns
// the normalized line, the raw filename, and whether the line carries a finding.
//
// The native tools disagree on their output shapes:
//   - gofmt -l:  "path/to/file.go"                 (filename only, no position)
//   - gocyclo:   "15 pkg Func path/to/file.go:12:1" (complexity-prefixed)
//   - go vet / misspell / ineffassign:
//     "path/to/file.go:line:col: message"          (already canonical)
func normalizeToolLine(line, enabledCheck string) (normalized, filename string, ok bool) {
	line = strings.TrimSpace(line)
	if line == "" {
		return "", "", false
	}

	// Native tools emit OS-native separators (backslash on Windows), but the
	// rest of the pipeline (skip checks, display names, file URLs) assumes
	// forward slashes. Normalize here so parsing is platform-independent.
	line = strings.ReplaceAll(line, "\\", "/")
	line = strings.TrimPrefix(line, "./")

	switch {
	case strings.Contains(enabledCheck, "gofmt"):
		// gofmt only lists offending files; synthesise a position so the rest
		// of the pipeline can report the file as a single issue.
		if !strings.HasSuffix(line, ".go") {
			return "", "", false
		}
		return line + ":1:1: file is not gofmt-ed with -s", line, true

	case strings.Contains(enabledCheck, "cyclo"):
		// "15 pkg Func file.go:line:col"
		fields := strings.Fields(line)
		if len(fields) < 4 {
			return "", "", false
		}
		loc := fields[len(fields)-1] // file.go:line:col
		fn := strings.Split(loc, ":")[0]
		msg := fmt.Sprintf("cyclomatic complexity %s for function %s", fields[0], fields[2])
		return loc + ": " + msg, fn, true

	default:
		// Already "file:line:col: message". Ignore any tool diagnostics that
		// do not follow that shape (e.g. build errors on stderr).
		parts := strings.SplitN(line, ":", 4)
		if len(parts) < 4 {
			return "", "", false
		}
		if _, err := strconv.Atoi(strings.TrimSpace(parts[1])); err != nil {
			return "", "", false
		}
		return line, parts[0], true
	}
}

func getFileSummaryMap(out *bufio.Scanner, dir, enabledCheck string) (map[string]FileSummary, error) {
	fsMap := make(map[string]FileSummary)
outer:
	for out.Scan() {
		normalized, filename, ok := normalizeToolLine(out.Text(), enabledCheck)
		if !ok {
			continue
		}

		// normalizeToolLine already converted separators to forward slashes,
		// so filename uses "/" regardless of the host OS.
		if dir != "" && !strings.Contains(filename, dir) {
			filename = strings.TrimSuffix(dir, "/") + "/" + filename
		}

		for _, skip := range skipSuffixes {
			if strings.HasSuffix(filename, skip) {
				continue outer
			}
		}

		for _, skip := range skipDirs {
			if strings.Contains(filename, fmt.Sprintf("/%s/", skip)) {
				continue outer
			}
		}

		if autoGenerated(filename) {
			continue outer
		}

		filename = strings.TrimPrefix(filename, "_repos/src")
		dfn := displayFilename(filename)
		fu := fileURL(filename)
		fs := fsMap[dfn]
		if fs.Filename == "" {
			fs.Filename = dfn
			fs.FileURL = fu
		}
		err := fs.AddError(normalized)
		if err != nil {
			return nil, err
		}
		fsMap[dfn] = fs
	}

	return fsMap, nil
}

// enabledCheckName returns the name of the check that a command enables. The
// name is used elsewhere to pick the right argument builder and output parser.
func enabledCheckName(command []string) string {
	// "go vet" is the only two-word command we invoke; every other native
	// tool identifies itself by its binary name.
	if command[0] == "go" && len(command) > 1 {
		return command[1]
	}
	return command[0]
}

// buildToolParams builds the argument list for the given command and target dir.
// Each supported native tool takes a slightly different set of positional
// arguments, so we branch on the enabled check.
func buildToolParams(dir, enabledCheck string, command []string) []string {
	params := command[1:]

	switch {
	case strings.Contains(enabledCheck, "vet"):
		// go vet is module-aware and expects a package pattern.
		params = append(params, "./...")
	case strings.Contains(enabledCheck, "staticcheck"):
		params = append(params, "./...")
	default:
		// gofmt, gocyclo, misspell and ineffassign all accept a directory and
		// walk it recursively.
		params = append(params, dir)
	}

	return params
}

// runTool executes the command and returns the failing file summaries.
func runTool(dir, enabledCheck string, command, params []string) ([]FileSummary, error) {
	cmd := exec.Command(command[0], params...)

	// Module-aware tools must run from within the target module so that the
	// "./..." package pattern resolves correctly.
	moduleAware := strings.Contains(enabledCheck, "vet") || strings.Contains(enabledCheck, "staticcheck")
	parseDir := dir
	if moduleAware {
		cmd.Dir = dir
		parseDir = ""
	}

	// Different tools report findings on stdout (gofmt, gocyclo, misspell,
	// ineffassign) or stderr (go vet), so we merge both streams.
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return []FileSummary{}, err
	}
	cmd.Stderr = cmd.Stdout

	if err := cmd.Start(); err != nil {
		return []FileSummary{}, err
	}

	out := bufio.NewScanner(stdout)

	// the same file can appear multiple times out of order
	// in the output, so we can't go line by line, have to store
	// a map of filename to FileSummary
	fsMap, err := getFileSummaryMap(out, parseDir, enabledCheck)
	if err != nil {
		return []FileSummary{}, err
	}

	if err := out.Err(); err != nil {
		return []FileSummary{}, err
	}

	var failed = []FileSummary{}
	for _, v := range fsMap {
		failed = append(failed, v)
	}

	if err := waitToolCmd(cmd); err != nil {
		return failed, err
	}

	return failed, nil
}

// waitToolCmd waits for the command to finish, tolerating an exit status of 1
// which some tools (for example go vet) use to signal that files failed checks.
func waitToolCmd(cmd *exec.Cmd) error {
	err := cmd.Wait()
	exitErr, ok := err.(*exec.ExitError)
	if !ok {
		return nil
	}

	status, ok := exitErr.Sys().(syscall.WaitStatus)
	if !ok {
		return err
	}

	if status.ExitStatus() != 1 {
		return err
	}

	return nil
}

// toolScore computes the passing score given the checked filenames and failures.
func toolScore(filenames []string, failed []FileSummary) (float64, error) {
	if len(filenames) == 1 {
		lc, err := lineCount(filenames[0])
		if err != nil {
			return 0, err
		}

		var errors int
		if len(failed) != 0 {
			errors = len(failed[0].Errors)
		}

		return float64(lc-errors) / float64(lc), nil
	}

	return float64(len(filenames)-len(failed)) / float64(len(filenames)), nil
}

// GoTool runs a given go command (for example gofmt, go tool vet)
// on a directory
func GoTool(dir string, filenames, command []string) (float64, []FileSummary, error) {
	enabledCheck := enabledCheckName(command)

	// temporary disabling of misspell as it's the slowest
	// command right now
	if strings.Contains(enabledCheck, "misspell") && len(filenames) > 300 {
		log.Println("disabling misspell on large repo...")
		return 1, []FileSummary{}, nil
	}

	if strings.Contains(enabledCheck, "ineffassign") && len(filenames) > 100 {
		log.Println("disabling ineffassign on large repo...")
		return 1, []FileSummary{}, nil
	}

	params := buildToolParams(dir, enabledCheck, command)

	failed, err := runTool(dir, enabledCheck, command, params)
	if err != nil {
		return 0, failed, err
	}

	score, err := toolScore(filenames, failed)
	if err != nil {
		return 0, failed, err
	}

	return score, failed, nil
}
